import { MigrationInterface, QueryRunner } from "typeorm";

export class AddPinnedArchivedToConversationMembers1767972872335 implements MigrationInterface {
    name = 'AddPinnedArchivedToConversationMembers1767972872335'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "scheduling"."job_executions_status_enum" AS ENUM('running', 'completed', 'failed', 'timeout', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "scheduling"."job_executions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "job_id" uuid NOT NULL, "status" "scheduling"."job_executions_status_enum" NOT NULL DEFAULT 'running', "started_at" TIMESTAMP NOT NULL, "completed_at" TIMESTAMP, "duration_ms" integer, "output" text, "error_message" text, "error_details" text, "metadata" text NOT NULL DEFAULT '{}', "worker_id" character varying(100), "queue_name" character varying(100), "priority" integer, "retry_attempt" integer NOT NULL DEFAULT '0', "execution_context" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8065e5e94f2131484c1af3c8553" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3d8444804ffed4f39df4713a6a" ON "scheduling"."job_executions" ("job_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d535194a711ff4a17987ddedb3" ON "scheduling"."job_executions" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_3b02402f8f3ff3027c86d55292" ON "scheduling"."job_executions" ("started_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_4fe9a8b1ff7f073b110be8a769" ON "scheduling"."job_executions" ("status", "started_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_f5f34b74eb2f22951822a92b47" ON "scheduling"."job_executions" ("job_id", "started_at") `);
        await queryRunner.query(`CREATE TYPE "scheduling"."jobs_type_enum" AS ENUM('message_delivery', 'notification', 'cleanup', 'maintenance', 'report', 'analytics', 'backup', 'sync')`);
        await queryRunner.query(`CREATE TYPE "scheduling"."jobs_status_enum" AS ENUM('pending', 'running', 'completed', 'failed', 'paused', 'cancelled', 'retry')`);
        await queryRunner.query(`CREATE TABLE "scheduling"."jobs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "type" "scheduling"."jobs_type_enum" NOT NULL, "status" "scheduling"."jobs_status_enum" NOT NULL DEFAULT 'pending', "payload" text NOT NULL, "priority" integer NOT NULL DEFAULT '1', "max_retries" integer NOT NULL DEFAULT '3', "retry_count" integer NOT NULL DEFAULT '0', "metadata" text NOT NULL DEFAULT '{}', "started_at" TIMESTAMP, "completed_at" TIMESTAMP, "failed_at" TIMESTAMP, "error_message" text, "error_details" text, "next_retry_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_cf0a6c42b72fcc7f7c237def345" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a0c30e3eb9649fe7fbcd336a63" ON "scheduling"."jobs" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_14d95a4e993e07ece3f6565831" ON "scheduling"."jobs" ("priority", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_a99ac650550679ccd793c564b1" ON "scheduling"."jobs" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_dc6f555dc06b89ce79ca00685b" ON "scheduling"."jobs" ("status", "type") `);
        await queryRunner.query(`CREATE TYPE "scheduling"."schedules_status_enum" AS ENUM('active', 'inactive', 'expired', 'paused')`);
        await queryRunner.query(`CREATE TABLE "scheduling"."schedules" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "job_id" uuid NOT NULL, "cron_expression" character varying(100) NOT NULL, "timezone" character varying(50) NOT NULL DEFAULT 'UTC', "start_at" TIMESTAMP, "end_at" TIMESTAMP, "is_active" boolean NOT NULL DEFAULT true, "status" "scheduling"."schedules_status_enum" NOT NULL DEFAULT 'active', "last_execution" TIMESTAMP, "next_execution" TIMESTAMP, "execution_count" integer NOT NULL DEFAULT '0', "max_executions" integer, "metadata" text NOT NULL DEFAULT '{}', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_886b66753e6476e863538391aa" UNIQUE ("job_id"), CONSTRAINT "PK_7e33fc2ea755a5765e3564e66dd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ff3fdb039f1f38244347cca44e" ON "scheduling"."schedules" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_b80fb4d37ef9d5e1948a46d9d3" ON "scheduling"."schedules" ("next_execution") `);
        await queryRunner.query(`CREATE INDEX "IDX_c419dee98aa2d344d1f2e233dc" ON "scheduling"."schedules" ("cron_expression") `);
        await queryRunner.query(`CREATE INDEX "IDX_9a2167dffbd8091066331389bd" ON "scheduling"."schedules" ("is_active", "next_execution") `);
        await queryRunner.query(`CREATE TABLE "messaging"."conversation_members" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "conversation_id" uuid NOT NULL, "user_id" uuid NOT NULL, "settings" text NOT NULL DEFAULT '{}', "is_pinned" boolean NOT NULL DEFAULT false, "is_archived" boolean NOT NULL DEFAULT false, "archived_at" TIMESTAMP, "joined_at" TIMESTAMP NOT NULL, "last_read_at" TIMESTAMP, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_5fa9076068b6f2a26fb793d2439" UNIQUE ("conversation_id", "user_id"), CONSTRAINT "PK_33146a476696a973a14d931e675" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a46c76be8f62c4b00a835cdc37" ON "messaging"."conversation_members" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_548e9b6dc4507150eb74cb82e8" ON "messaging"."conversation_members" ("conversation_id", "is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_5da9c25bf1f0ab1b8dba30f673" ON "messaging"."conversation_members" ("user_id", "is_active") `);
        await queryRunner.query(`CREATE TYPE "messaging"."conversations_type_enum" AS ENUM('direct', 'group')`);
        await queryRunner.query(`CREATE TABLE "messaging"."conversations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "messaging"."conversations_type_enum" NOT NULL DEFAULT 'direct', "external_group_id" uuid, "metadata" text NOT NULL DEFAULT '{}', "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ee34f4f7ced4ec8681f26bf04ef" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7018433f850e2836a7d9df1b9d" ON "messaging"."conversations" ("updated_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_163c34017258dba8e1f7d6f82c" ON "messaging"."conversations" ("external_group_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f978c9f919fbeec98e311c980c" ON "messaging"."conversations" ("type", "is_active") `);
        await queryRunner.query(`CREATE TABLE "messaging"."delivery_statuses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "message_id" uuid NOT NULL, "user_id" uuid NOT NULL, "delivered_at" TIMESTAMP, "read_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_cb4aef4a0d89c986893c65ed1de" UNIQUE ("message_id", "user_id"), CONSTRAINT "PK_9879904dd0e500b28523986648a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6dfabb731cfd5ae7cc1f916772" ON "messaging"."delivery_statuses" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_93777421f5aa1c998cb1bc705b" ON "messaging"."delivery_statuses" ("message_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_81156e56738561bc496fd62a2c" ON "messaging"."delivery_statuses" ("user_id", "delivered_at") `);
        await queryRunner.query(`CREATE TABLE "messaging"."message_reactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "message_id" uuid NOT NULL, "user_id" uuid NOT NULL, "reaction" character varying(50) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_405efd1bc25df76b345fc0ad967" UNIQUE ("message_id", "user_id", "reaction"), CONSTRAINT "PK_654a9f0059ff93a8f156be66a5b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b6d3eda2f99b64016d6a4cf112" ON "messaging"."message_reactions" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ce61e365d81a9dfc15cd36513b" ON "messaging"."message_reactions" ("message_id") `);
        await queryRunner.query(`CREATE TYPE "messaging"."messages_message_type_enum" AS ENUM('text', 'media', 'system', 'notification')`);
        await queryRunner.query(`CREATE TABLE "messaging"."messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "conversation_id" uuid NOT NULL, "sender_id" uuid NOT NULL, "message_type" "messaging"."messages_message_type_enum" NOT NULL DEFAULT 'text', "content" text, "metadata" text NOT NULL DEFAULT '{}', "client_random" bigint, "reply_to_id" uuid, "sent_at" TIMESTAMP NOT NULL, "edited_at" TIMESTAMP, "is_deleted" boolean NOT NULL DEFAULT false, "deleted_for_everyone" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_18325f38ae6de43878487eff986" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3bc55a7c3f9ed54b520bb5cfe2" ON "messaging"."messages" ("conversation_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_cc300998778c9527f5a516f0fb" ON "messaging"."messages" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "IDX_c2bc726fd86d8f91c4868a1056" ON "messaging"."messages" ("sent_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_22133395bd13b970ccd0c34ab2" ON "messaging"."messages" ("sender_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_5dc244350d4aeea419f28acb07" ON "messaging"."messages" ("conversation_id", "sent_at") `);
        await queryRunner.query(`CREATE TABLE "users_auth" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "phone_number" character varying(20) NOT NULL, "two_factor_secret" character varying(255), "two_factor_enabled" boolean NOT NULL DEFAULT false, "last_authenticated_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_6c007a7e6e36a8a08aaf93ad7c6" UNIQUE ("phone_number"), CONSTRAINT "PK_32ddc1ae708e8261a870a6eb3e6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "devices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "device_name" character varying(100) NOT NULL, "device_type" character varying(20) NOT NULL, "device_fingerprint" character varying(255) NOT NULL, "model" character varying(100), "os_version" character varying(50), "app_version" character varying(20), "fcm_token" character varying(255), "apns_token" character varying(255), "public_key" text NOT NULL, "last_active" TIMESTAMP NOT NULL DEFAULT now(), "ip_address" character varying(45), "is_verified" boolean NOT NULL DEFAULT false, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_b7c1a1b1d1eff0d845ae768113f" UNIQUE ("device_fingerprint"), CONSTRAINT "PK_b1514758245c12daf43486dd1f0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_32ad28d706d855cf84922c3395" ON "devices" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_5d3bce74e601e20e2b1eef4af2" ON "devices" ("last_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_5e9bee993b4ce35c3606cda194" ON "devices" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "signed_prekeys" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "key_id" integer NOT NULL, "public_key" text NOT NULL, "signature" text NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "expires_at" TIMESTAMP NOT NULL, CONSTRAINT "UQ_845b034d01fcff9d8e615631d17" UNIQUE ("user_id", "key_id"), CONSTRAINT "PK_4ed882812c30ac9cd9287b1cbc2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9c4efc0bdba3a988e1d02207fc" ON "signed_prekeys" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "prekeys" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "key_id" integer NOT NULL, "public_key" text NOT NULL, "is_one_time" boolean NOT NULL DEFAULT true, "is_used" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_0797e3a749446851a2ce65b6296" UNIQUE ("user_id", "key_id"), CONSTRAINT "PK_a21fef14afb09f1eda3f8841e86" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_add27ed72ba5fe9a0fb76b576c" ON "prekeys" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "login_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "device_id" uuid, "ip_address" character varying(45) NOT NULL, "user_agent" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "status" character varying(20) NOT NULL, CONSTRAINT "PK_fe377f36d49c39547cb6b9f0727" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_008a7582bcd8b53bba575e424a" ON "login_history" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_192bedb1c372c2eb71fc61ad39" ON "login_history" ("device_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ad9ce49cb73c0b33746a56b6bd" ON "login_history" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "identity_keys" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "public_key" text NOT NULL, "private_key_encrypted" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_db826dd4430e0a7e4a59982f5bc" UNIQUE ("user_id"), CONSTRAINT "PK_90fc3cac4458dc14643621096d7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "backup_codes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "code_hash" character varying(255) NOT NULL, "used" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "used_at" TIMESTAMP, CONSTRAINT "PK_34ab957382dbc57e8fb53f1638f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_70066ea80d2f4b871beda32633" ON "backup_codes" ("user_id") `);
        await queryRunner.query(`ALTER TABLE "scheduling"."job_executions" ADD CONSTRAINT "FK_3d8444804ffed4f39df4713a6a7" FOREIGN KEY ("job_id") REFERENCES "scheduling"."jobs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scheduling"."schedules" ADD CONSTRAINT "FK_886b66753e6476e863538391aad" FOREIGN KEY ("job_id") REFERENCES "scheduling"."jobs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messaging"."conversation_members" ADD CONSTRAINT "FK_36340a1704b039608e34244511f" FOREIGN KEY ("conversation_id") REFERENCES "messaging"."conversations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messaging"."delivery_statuses" ADD CONSTRAINT "FK_93777421f5aa1c998cb1bc705bf" FOREIGN KEY ("message_id") REFERENCES "messaging"."messages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messaging"."message_reactions" ADD CONSTRAINT "FK_ce61e365d81a9dfc15cd36513b0" FOREIGN KEY ("message_id") REFERENCES "messaging"."messages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messaging"."messages" ADD CONSTRAINT "FK_3bc55a7c3f9ed54b520bb5cfe23" FOREIGN KEY ("conversation_id") REFERENCES "messaging"."conversations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messaging"."messages" ADD CONSTRAINT "FK_54e66104dd534ed1c191e44096f" FOREIGN KEY ("reply_to_id") REFERENCES "messaging"."messages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "devices" ADD CONSTRAINT "FK_5e9bee993b4ce35c3606cda194c" FOREIGN KEY ("user_id") REFERENCES "users_auth"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "signed_prekeys" ADD CONSTRAINT "FK_9c4efc0bdba3a988e1d02207fc7" FOREIGN KEY ("user_id") REFERENCES "users_auth"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prekeys" ADD CONSTRAINT "FK_add27ed72ba5fe9a0fb76b576c3" FOREIGN KEY ("user_id") REFERENCES "users_auth"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "login_history" ADD CONSTRAINT "FK_ad9ce49cb73c0b33746a56b6bd1" FOREIGN KEY ("user_id") REFERENCES "users_auth"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "login_history" ADD CONSTRAINT "FK_192bedb1c372c2eb71fc61ad394" FOREIGN KEY ("device_id") REFERENCES "devices"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "identity_keys" ADD CONSTRAINT "FK_db826dd4430e0a7e4a59982f5bc" FOREIGN KEY ("user_id") REFERENCES "users_auth"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "backup_codes" ADD CONSTRAINT "FK_70066ea80d2f4b871beda32633b" FOREIGN KEY ("user_id") REFERENCES "users_auth"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "backup_codes" DROP CONSTRAINT "FK_70066ea80d2f4b871beda32633b"`);
        await queryRunner.query(`ALTER TABLE "identity_keys" DROP CONSTRAINT "FK_db826dd4430e0a7e4a59982f5bc"`);
        await queryRunner.query(`ALTER TABLE "login_history" DROP CONSTRAINT "FK_192bedb1c372c2eb71fc61ad394"`);
        await queryRunner.query(`ALTER TABLE "login_history" DROP CONSTRAINT "FK_ad9ce49cb73c0b33746a56b6bd1"`);
        await queryRunner.query(`ALTER TABLE "prekeys" DROP CONSTRAINT "FK_add27ed72ba5fe9a0fb76b576c3"`);
        await queryRunner.query(`ALTER TABLE "signed_prekeys" DROP CONSTRAINT "FK_9c4efc0bdba3a988e1d02207fc7"`);
        await queryRunner.query(`ALTER TABLE "devices" DROP CONSTRAINT "FK_5e9bee993b4ce35c3606cda194c"`);
        await queryRunner.query(`ALTER TABLE "messaging"."messages" DROP CONSTRAINT "FK_54e66104dd534ed1c191e44096f"`);
        await queryRunner.query(`ALTER TABLE "messaging"."messages" DROP CONSTRAINT "FK_3bc55a7c3f9ed54b520bb5cfe23"`);
        await queryRunner.query(`ALTER TABLE "messaging"."message_reactions" DROP CONSTRAINT "FK_ce61e365d81a9dfc15cd36513b0"`);
        await queryRunner.query(`ALTER TABLE "messaging"."delivery_statuses" DROP CONSTRAINT "FK_93777421f5aa1c998cb1bc705bf"`);
        await queryRunner.query(`ALTER TABLE "messaging"."conversation_members" DROP CONSTRAINT "FK_36340a1704b039608e34244511f"`);
        await queryRunner.query(`ALTER TABLE "scheduling"."schedules" DROP CONSTRAINT "FK_886b66753e6476e863538391aad"`);
        await queryRunner.query(`ALTER TABLE "scheduling"."job_executions" DROP CONSTRAINT "FK_3d8444804ffed4f39df4713a6a7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_70066ea80d2f4b871beda32633"`);
        await queryRunner.query(`DROP TABLE "backup_codes"`);
        await queryRunner.query(`DROP TABLE "identity_keys"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ad9ce49cb73c0b33746a56b6bd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_192bedb1c372c2eb71fc61ad39"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_008a7582bcd8b53bba575e424a"`);
        await queryRunner.query(`DROP TABLE "login_history"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_add27ed72ba5fe9a0fb76b576c"`);
        await queryRunner.query(`DROP TABLE "prekeys"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9c4efc0bdba3a988e1d02207fc"`);
        await queryRunner.query(`DROP TABLE "signed_prekeys"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5e9bee993b4ce35c3606cda194"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5d3bce74e601e20e2b1eef4af2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_32ad28d706d855cf84922c3395"`);
        await queryRunner.query(`DROP TABLE "devices"`);
        await queryRunner.query(`DROP TABLE "users_auth"`);
        await queryRunner.query(`DROP INDEX "messaging"."IDX_5dc244350d4aeea419f28acb07"`);
        await queryRunner.query(`DROP INDEX "messaging"."IDX_22133395bd13b970ccd0c34ab2"`);
        await queryRunner.query(`DROP INDEX "messaging"."IDX_c2bc726fd86d8f91c4868a1056"`);
        await queryRunner.query(`DROP INDEX "messaging"."IDX_cc300998778c9527f5a516f0fb"`);
        await queryRunner.query(`DROP INDEX "messaging"."IDX_3bc55a7c3f9ed54b520bb5cfe2"`);
        await queryRunner.query(`DROP TABLE "messaging"."messages"`);
        await queryRunner.query(`DROP TYPE "messaging"."messages_message_type_enum"`);
        await queryRunner.query(`DROP INDEX "messaging"."IDX_ce61e365d81a9dfc15cd36513b"`);
        await queryRunner.query(`DROP INDEX "messaging"."IDX_b6d3eda2f99b64016d6a4cf112"`);
        await queryRunner.query(`DROP TABLE "messaging"."message_reactions"`);
        await queryRunner.query(`DROP INDEX "messaging"."IDX_81156e56738561bc496fd62a2c"`);
        await queryRunner.query(`DROP INDEX "messaging"."IDX_93777421f5aa1c998cb1bc705b"`);
        await queryRunner.query(`DROP INDEX "messaging"."IDX_6dfabb731cfd5ae7cc1f916772"`);
        await queryRunner.query(`DROP TABLE "messaging"."delivery_statuses"`);
        await queryRunner.query(`DROP INDEX "messaging"."IDX_f978c9f919fbeec98e311c980c"`);
        await queryRunner.query(`DROP INDEX "messaging"."IDX_163c34017258dba8e1f7d6f82c"`);
        await queryRunner.query(`DROP INDEX "messaging"."IDX_7018433f850e2836a7d9df1b9d"`);
        await queryRunner.query(`DROP TABLE "messaging"."conversations"`);
        await queryRunner.query(`DROP TYPE "messaging"."conversations_type_enum"`);
        await queryRunner.query(`DROP INDEX "messaging"."IDX_5da9c25bf1f0ab1b8dba30f673"`);
        await queryRunner.query(`DROP INDEX "messaging"."IDX_548e9b6dc4507150eb74cb82e8"`);
        await queryRunner.query(`DROP INDEX "messaging"."IDX_a46c76be8f62c4b00a835cdc37"`);
        await queryRunner.query(`DROP TABLE "messaging"."conversation_members"`);
        await queryRunner.query(`DROP INDEX "scheduling"."IDX_9a2167dffbd8091066331389bd"`);
        await queryRunner.query(`DROP INDEX "scheduling"."IDX_c419dee98aa2d344d1f2e233dc"`);
        await queryRunner.query(`DROP INDEX "scheduling"."IDX_b80fb4d37ef9d5e1948a46d9d3"`);
        await queryRunner.query(`DROP INDEX "scheduling"."IDX_ff3fdb039f1f38244347cca44e"`);
        await queryRunner.query(`DROP TABLE "scheduling"."schedules"`);
        await queryRunner.query(`DROP TYPE "scheduling"."schedules_status_enum"`);
        await queryRunner.query(`DROP INDEX "scheduling"."IDX_dc6f555dc06b89ce79ca00685b"`);
        await queryRunner.query(`DROP INDEX "scheduling"."IDX_a99ac650550679ccd793c564b1"`);
        await queryRunner.query(`DROP INDEX "scheduling"."IDX_14d95a4e993e07ece3f6565831"`);
        await queryRunner.query(`DROP INDEX "scheduling"."IDX_a0c30e3eb9649fe7fbcd336a63"`);
        await queryRunner.query(`DROP TABLE "scheduling"."jobs"`);
        await queryRunner.query(`DROP TYPE "scheduling"."jobs_status_enum"`);
        await queryRunner.query(`DROP TYPE "scheduling"."jobs_type_enum"`);
        await queryRunner.query(`DROP INDEX "scheduling"."IDX_f5f34b74eb2f22951822a92b47"`);
        await queryRunner.query(`DROP INDEX "scheduling"."IDX_4fe9a8b1ff7f073b110be8a769"`);
        await queryRunner.query(`DROP INDEX "scheduling"."IDX_3b02402f8f3ff3027c86d55292"`);
        await queryRunner.query(`DROP INDEX "scheduling"."IDX_d535194a711ff4a17987ddedb3"`);
        await queryRunner.query(`DROP INDEX "scheduling"."IDX_3d8444804ffed4f39df4713a6a"`);
        await queryRunner.query(`DROP TABLE "scheduling"."job_executions"`);
        await queryRunner.query(`DROP TYPE "scheduling"."job_executions_status_enum"`);
    }

}
